#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import subprocess
from pathlib import Path


def srt_time_to_ass(srt_time):
    """安全的时间转换函数"""
    try:
        t = str(srt_time).replace(",", ".")
        t = t.lstrip("0")
        if t.startswith(":"):
            t = "0" + t
        return t
    except Exception:
        return str(srt_time)


def parse_srt(srt_path):
    """解析SRT文件"""
    encodings = ["utf-8", "utf-8-sig", "latin-1", "cp1252"]
    lines = None

    for encoding in encodings:
        try:
            with open(srt_path, "r", encoding=encoding, errors="ignore") as f:
                lines = f.readlines()
                print(f"[DEBUG] 使用编码 {encoding} 成功读取文件")
                break
        except Exception as e:
            print(f"[DEBUG] 编码 {encoding} 失败: {e}")
            continue

    if lines is None:
        with open(srt_path, "rb") as f:
            raw_data = f.read()
            lines = raw_data.decode("utf-8", errors="replace").splitlines()

    blocks = []
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        if line and re.match(r"^\d+$", line):
            if i + 1 < len(lines):
                time_line = lines[i + 1].strip()
                if " --> " in time_line:
                    start, end = time_line.split(" --> ")

                    text_lines = []
                    j = i + 2
                    while j < len(lines):
                        text_line = lines[j].strip()
                        if not text_line:
                            break
                        text_lines.append(text_line)
                        j += 1

                    blocks.append(
                        {
                            "start": start.strip(),
                            "end": end.strip(),
                            "text": " ".join(text_lines),
                        }
                    )

                    i = j
                    continue

        i += 1

    print(f"[DEBUG] 解析完成: {len(blocks)} 个字幕块")
    return blocks


def to_karaoke_ruby(text, file_name):
    """生成卡拉OK振假名"""
    replacements = [
        ("<br/>", r"{\k1}"),
        ("<ruby>", r"{\k1}"),
        ("<rp>(</rp><rt>", "|<"),
        ("</rt><rp>)</rp></ruby>", r"{\k1}"),
        (r"{\k1}{\k1}", r"{\k1}"),
    ]

    result = subprocess.run(
        ["bun", file_name, text],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )

    if result.returncode == 0:
        final_result = result.stdout.strip().replace('"', "")
        for old, new in replacements:
            final_result = final_result.replace(old, new)
        if final_result[:5] != r"{\k1}":
            final_result = r"{\k1}" + final_result
        return final_result

    raise RuntimeError(f"执行失败: {result.stderr}")


def convert_srt_to_ass_karaoke(srt_path, ass_path):
    """转换SRT到ASS卡拉OK字幕"""
    blocks = parse_srt(srt_path)

    ass_header = r"""[Script Info]
; Script generated by Aegisub 3.4.2
; http://www.aegisub.org/
Title: 日语振假名字幕
ScriptType: v4.00+
WrapStyle: 0
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,16,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    ass_events = []

    for block in blocks:
        try:
            start_ass = srt_time_to_ass(block["start"])
            end_ass = srt_time_to_ass(block["end"])
            text = block["text"]
        except (KeyError, TypeError) as e:
            print(f"[WARNING] 跳过无效的block: {e}")
            continue

        file_name = "kuroshiro.mjs"
        ruby_text = to_karaoke_ruby(text, file_name)
        ass_events.append(
            f"Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{ruby_text}\n",
        )

    with open(ass_path, "w", encoding="utf-8") as f:
        f.write(ass_header)
        f.writelines(ass_events)

    print(f"成功生成ASS文件: {ass_path}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("用法: python simple_test.py <srt文件> [ass输出文件]")
        sys.exit(1)

    srt_file = sys.argv[1]
    ass_file = (
        sys.argv[2] if len(sys.argv) > 2 else srt_file.replace(".srt", "_karaoke.ass")
    )

    convert_srt_to_ass_karaoke(srt_file, ass_file)
    print(f"转换完成: {ass_file}")
