import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';
import K from 'kuroshiro';
import KuromojiAnalyzer from 'kuroshiro-analyzer-kuromoji';
const Kuroshiro = K.default;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let kuroshiroInstance = null;
let kuroshiroInitPromise = null;

function srtTimeToAss(srtTime) {
  try {
    return String(srtTime).replace(',', '.').replace(/^0+/, '').replace(/^:/, '0:');
  } catch {
    return String(srtTime);
  }
}

function readFileContent(filePath) {
  const encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252'];
  for (const enc of encodings) {
    try {
      return fs.readFileSync(filePath, { encoding: enc });
    } catch {
      continue;
    }
  }
  return fs.readFileSync(filePath, { encoding: 'utf-8', flag: 'r' });
}

function parseSrt(filePath) {
  const content = readFileContent(filePath);
  const lines = content.split(/\r?\n/);
  const blocks = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i].trim();

    if (line && /^\d+$/.test(line)) {
      const timeLine = lines[i + 1]?.trim();
      if (timeLine && timeLine.includes(' --> ')) {
        const [start, end] = timeLine.split(' --> ');
        const textLines = [];
        let j = i + 2;
        while (j < lines.length) {
          const textLine = lines[j].trim();
          if (!textLine) break;
          textLines.push(textLine);
          j++;
        }

        blocks.push({
          start: start.trim(),
          end: end.trim(),
          text: textLines.join(' '),
        });

        i = j;
        continue;
      }
    }
    i++;
  }

  return blocks;
}

function parseAss(filePath) {
  const content = readFileContent(filePath);
  const lines = content.split(/\r?\n/);
  const blocks = [];
  let inEvents = false;
  let startIdx = -1;
  let endIdx = -1;
  let textIdx = -1;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (line === '[Events]') {
      inEvents = true;
      continue;
    }

    if (!inEvents) continue;
    if (line.startsWith('[')) break;

    const upper = line.toUpperCase();
    if (upper.startsWith('FORMAT:')) {
      const fields = line.slice(7).split(',').map(f => f.trim());
      startIdx = fields.indexOf('Start');
      endIdx = fields.indexOf('End');
      textIdx = fields.indexOf('Text');
      continue;
    }

    if (!upper.startsWith('DIALOGUE:')) continue;
    if (startIdx < 0 || endIdx < 0 || textIdx < 0) continue;

    const parts = line.split(',');
    if (parts.length <= Math.max(startIdx, endIdx, textIdx)) continue;

    const start = parts[startIdx].trim();
    const end = parts[endIdx].trim();
    const text = parts.slice(textIdx).join(',').trim();

    if (start && end) {
      blocks.push({ start, end, text });
    }
  }

  return blocks;
}

function parseSubtitleFile(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === '.ass' || ext === '.ssa') {
    return parseAss(filePath);
  }
  return parseSrt(filePath);
}

async function toKaraokeRuby(text) {
  if (!kuroshiroInitPromise) {
    kuroshiroInitPromise = (async () => {
      kuroshiroInstance = new Kuroshiro();
      const dictPath = path.join(__dirname, 'node_modules', 'kuromoji', 'dict');
      const analyzer = new KuromojiAnalyzer({ dictPath });
      await kuroshiroInstance.init(analyzer);
    })();
  }
  await kuroshiroInitPromise;

  const result = await kuroshiroInstance.convert(text, {
    mode: 'furigana',
    to: 'hiragana',
  });

  let finalResult = result.replace(/"/g, '');
  const replacements = [
    ['<br/>', '{\\k1}'],
    ['<ruby>', '{\\k1}'],
    ['<rp>(</rp><rt>', '|<'],
    ['</rt><rp>)</rp></ruby>', '{\\k1}'],
    ['{\\k1}{\\k1}', '{\\k1}'],
    ['{\\k1}二|<に{\\k1}人|<にん{\\k1}', '{\\k1}二人|<ふたり{\\k1}'],
    ['{\\k1}一|<いち{\\k1}人|<にん{\\k1}', '{\\k1}一人|<ひとり{\\k1}'],
  ];

  for (const [old, rep] of replacements) {
    finalResult = finalResult.replaceAll(old, rep);
  }

  if (!finalResult.startsWith('{\\k1}')) {
    finalResult = '{\\k1}' + finalResult;
  }

  return finalResult;
}

function convertSrtToAss(srtPath, assPath, blocks) {
  const assHeader = `[Script Info]
; Script generated by Aegisub 3.4.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,16,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,template noblank syl,{\\an5\\pos($center,$middle)}
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,template noblank furi,{\\an5\\pos($center,!$middle+5!)}
`;

  const assEvents = blocks.map(b => {
    const start = srtTimeToAss(b.start);
    const end = srtTimeToAss(b.end);
    return `Dialogue: 0,${start},${end},Default,,0,0,0,,${b.text}\n`;
  });

  fs.mkdirSync(path.dirname(assPath), { recursive: true });
  fs.writeFileSync(assPath, assHeader + assEvents.join(''), 'utf-8');
}

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 560,
    height: 520,
    resizable: false,
    autoHideMenuBar: true,
    title: '日语非卡拉OK字幕注音模板生成程序',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'renderer', 'index.html'));
}

ipcMain.handle('select-file', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: '选择字幕文件',
    filters: [
      { name: '字幕文件', extensions: ['srt', 'ass', 'ssa'] },
      { name: 'All files', extensions: ['*'] },
    ],
    properties: ['openFile'],
  });

  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

ipcMain.handle('select-save-file', async () => {
  const result = await dialog.showSaveDialog(mainWindow, {
    title: '保存合并后的字幕',
    filters: [
      { name: 'SRT 字幕', extensions: ['srt'] },
      { name: 'ASS 字幕', extensions: ['ass'] },
      { name: 'All files', extensions: ['*'] },
    ],
    defaultPath: 'merged_subtitle.srt',
  });

  if (result.canceled || !result.filePath) return null;
  return result.filePath;
});

ipcMain.handle('merge-srt', async (_event, { file1, file2, swap, outputPath }) => {
  try {
    const blocks1 = parseSubtitleFile(file1);
    const blocks2 = parseSubtitleFile(file2);

    if (blocks1.length !== blocks2.length) {
      return {
        success: false,
        error: `字幕行数不一致 (${blocks1.length} vs ${blocks2.length})，无法合并`,
      };
    }

    const merged = blocks1.map((b, i) => {
      const text1 = b.text.trim();
      const text2 = blocks2[i].text.trim();
      let mergedText;
      if (swap) {
        mergedText = text2 + '\\N' + text1;
      } else {
        mergedText = text1 + '\\N' + text2;
      }
      return {
        start: b.start,
        end: b.end,
        text: mergedText,
      };
    });

    const content = merged.map((b, i) => {
      return `${i + 1}\n${b.start} --> ${b.end}\n${b.text}\n\n`;
    }).join('');

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, content, 'utf-8');

    return { success: true, outputPath, total: merged.length };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('convert-srt', async (_event, srtPath) => {
  try {
    const blocks = parseSubtitleFile(srtPath);
    const total = blocks.length;

    const results = await Promise.all(blocks.map(b => toKaraokeRuby(b.text)));
    for (let idx = 0; idx < blocks.length; idx++) {
      blocks[idx].text = results[idx];
    }

    const assPath = srtPath.replace(/\.(srt|ass|ssa)$/i, '.ass');
    convertSrtToAss(srtPath, assPath, blocks);

    return { success: true, assPath, total };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
