import re
from pathlib import Path
from tkinter import filedialog, messagebox

import customtkinter as ctk


def srt_time_to_ass(srt_time):
    """安全的时间转换函数"""
    try:
        t = str(srt_time).replace(",", ".")
        t = t.lstrip("0")
        if t.startswith(":"):
            t = "0" + t
        return t
    except Exception:
        # 如果转换失败，返回原始值
        return str(srt_time)


def parse_srt(srt_path):
    """解析SRT文件"""
    # 尝试多种编码方式
    encodings = ["utf-8", "utf-8-sig", "latin-1", "cp1252"]
    lines = None

    for encoding in encodings:
        try:
            with open(srt_path, "r", encoding=encoding, errors="ignore") as f:
                lines = f.readlines()
                print(f"[DEBUG] 使用编码 {encoding} 成功读取文件")
                break
        except Exception as e:
            print(f"[DEBUG] 编码 {encoding} 失败: {e}")
            continue

    if lines is None:
        # 最后使用二进制读取
        with open(srt_path, "rb") as f:
            raw_data = f.read()
            lines = raw_data.decode("utf-8", errors="replace").splitlines()

    blocks = []
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        # 检查是否是数字索引行
        if line and re.match(r"^\d+$", line):
            # 这是索引行，下一行是时间行
            if i + 1 < len(lines):
                time_line = lines[i + 1].strip()
                if " --> " in time_line:
                    start, end = time_line.split(" --> ")

                    # 收集文本行
                    text_lines = []
                    j = i + 2
                    while j < len(lines):
                        text_line = lines[j].strip()
                        if not text_line:  # 空行表示结束
                            break
                        text_lines.append(text_line)
                        j += 1

                    # 添加到blocks
                    blocks.append(
                        {
                            "start": start.strip(),
                            "end": end.strip(),
                            "text": " ".join(text_lines),
                        }
                    )

                    i = j  # 跳到下一块
                    continue

        i += 1

    print(f"[DEBUG] 解析完成: {len(blocks)} 个字幕块")
    return blocks


def to_karaoke_ruby(text):
    replacements = [
        ("<br/>", r"{\k1}"),
        ("<ruby>", r"{\k1}"),
        ("<rp>(</rp><rt>", "|<"),
        ("</rt><rp>)</rp></ruby>", r"{\k1}"),
        (r"{\k1}{\k1}", r"{\k1}"),
        (r"{\k1}二|<に{\k1}人|<にん{\k1}", r"{\k1}二人|<ふたり{\k1}"),
        (r"{\k1}一|<いち{\k1}人|<にん{\k1}", r"{\k1}一人|<ひとり{\k1}"),
    ]

    # 修复了导入问题，直接使用subprocess
    import subprocess
    import sys

    # 创建startupinfo对象以隐藏终端窗口
    startupinfo = None
    if sys.platform == "win32":
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = subprocess.SW_HIDE  # 隐藏窗口

    # 执行 Node.js/Bun 脚本并获取返回值
    result = subprocess.run(
        [
            "bun",
            "kuroshiro.mjs",
            text,
        ],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        startupinfo=startupinfo,  # 隐藏终端窗口
    )
    if result.returncode == 0:
        final_result = result.stdout.strip().replace('"', "")
        for old, new in replacements:
            final_result = final_result.replace(old, new)
        if final_result[:5] != r"{\k1}":
            final_result = r"{\k1}" + final_result
        return final_result
    raise RuntimeError(f"执行失败: {result.stderr}")


def convert_srt_to_ass_karaoke(srt_path, ass_path):
    blocks = parse_srt(srt_path)
    ass_header = r"""[Script Info]
; Script generated by Aegisub 3.4.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,16,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,template noblank syl,{\an5\pos($center,$middle)}
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,template noblank furi,{\an5\pos($center,$middle)}
"""

    ass_events = []
    for block in blocks:
        # 直接访问字典（parse_srt已确保是字典）
        try:
            start_ass = srt_time_to_ass(block["start"])
            end_ass = srt_time_to_ass(block["end"])
            text = block["text"]
        except (KeyError, TypeError) as e:
            print(f"[WARNING] 跳过无效的block: {e}")
            continue

        ruby_text = to_karaoke_ruby(text)
        ass_events.append(
            f"Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{ruby_text}\n",
        )

    with open(ass_path, "w", encoding="utf-8") as f:
        f.write(ass_header)
        f.writelines(ass_events)


def select_srt_file():
    file_path = filedialog.askopenfilename(
        title="选择SRT文件",
        filetypes=[("SRT files", "*.srt"), ("All files", "*.*")],
    )
    if file_path:
        srt_entry.configure(state="normal")
        srt_entry.delete(0, ctk.END)
        srt_entry.insert(0, file_path)
        srt_entry.configure(state="disabled")


def convert_to_ass():
    srt_path = srt_entry.get()
    if not srt_path:
        messagebox.showerror("错误：", "请选择一个SRT文件。")
        return

    ass_path = Path(srt_path).with_suffix(".ass")
    try:
        convert_srt_to_ass_karaoke(srt_path, ass_path)
        messagebox.showinfo("结果：", f"已转换成非卡拉OK注音模板: {ass_path}")
    except Exception as e:
        messagebox.showerror("错误：", f"转换中发生错误: {e}")


def center_window(app, width, height):
    screenwidth = app.winfo_screenwidth()
    screenheight = app.winfo_screenheight()
    size = "%dx%d+%d+%d" % (
        width,
        height,
        (screenwidth - width) / 2,
        (screenheight - height) / 2,
    )
    app.geometry(size)


# GUI メインウィンドウ
app = ctk.CTk()
app.title("日语非卡拉OK字幕注音模板生成程序")
width = 450
height = 200
center_window(app, width, height)

# 禁止用户调整窗口大小
app.resizable(False, False)

app.grid_columnconfigure((0, 1), weight=1)
# ファイル選択ボタンと表示フィールドを一行に配置
srt_entry = ctk.CTkEntry(app, placeholder_text="请选择SRT文件")
srt_entry.grid(row=0, column=0, padx=10, pady=(50, 20), sticky="ew", columnspan=4)

file_sel = ctk.CTkButton(app, text="文件选择", command=select_srt_file)
file_sel.grid(row=0, column=4, padx=10, pady=(50, 20), columnspan=1)
# 変換ボタン
start_chg = ctk.CTkButton(app, text="开始转换", command=convert_to_ass)
start_chg.grid(row=1, column=2, padx=0, pady=20, sticky="ew", columnspan=2)
# ウィンドウを表示
bzh = ctk.CTkLabel(app, text="作者B站：水橙汁", text_color="#FF6A6A")
bzh.grid(row=2, column=0)

if __name__ == "__main__":
    app.mainloop()
